services:
  imaotai-db:
    image: mysql:8.0.35
    container_name: imaotai-db
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: 'campus_imaotai'
    volumes:
      - ./volumes/mysql/data/:/var/lib/mysql/
      - ./volumes/mysql/logs:/logs
    command: [
          'mysqld',
          '--innodb-buffer-pool-size=80M',
          '--character-set-server=utf8mb4',
          '--collation-server=utf8mb4_unicode_ci',
          '--default-time-zone=+8:00',
          '--lower-case-table-names=1',
          '--default-authentication-plugin=mysql_native_password'
        ]
    networks:
      - imaotai_net

  imaotai-redis:
    image: redis:6.2.12
    container_name: imaotai-redis
    volumes:
      - ./volumes/redis/data/:/redis/data/
    networks:
      - imaotai_net

  imaotai-api:
    image: imaotai-api:latest
    build:
      context: .
      dockerfile: ./api.Dockerfile
    container_name: imaotai-api
    networks:
      - imaotai_net

  imaotai-web:
    image: imaotai-web:latest
    build:
      context: .
      dockerfile: ./web.Dockerfile
    container_name: imaotai-nginx
    volumes:
      - ./templates/nginx.conf:/etc/nginx/nginx.conf
      - ./volumes/nginx/log:/var/log/nginx
    privileged: true
    networks:
      - imaotai_net
    ports:
      - 8160:8160

networks:
  imaotai_net:
    name: imaotai_net