services:
  imaotai-db:
    image: imaotai-db:latest
    build:
      context: .
      dockerfile: ./mysql.Dockerfile
    container_name: imaotai-db
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
    volumes:
      - ./volumes/db/data/:/var/lib/mysql/
      - ./volumes/db/logs:/logs
    command: [
          'mysqld',
          '--innodb-buffer-pool-size=80M',
          '--character-set-server=utf8mb4',
          '--collation-server=utf8mb4_unicode_ci',
          '--default-time-zone=+8:00',
          '--lower-case-table-names=1',
          '--default-authentication-plugin=mysql_native_password'
        ]
    networks:
      - imaotai_net
    restart: always

  imaotai-redis:
    image: redis:6.2.12
    container_name: imaotai-redis
    volumes:
      - ./volumes/redis/data/:/redis/data/
    networks:
      - imaotai_net
    restart: always

  imaotai-api:
    image: imaotai-api:latest
    build:
      context: .
      dockerfile: ./api.Dockerfile
    container_name: imaotai-api
    networks:
      - imaotai_net
    depends_on:
      - imaotai-db
    restart: always

  imaotai-web:
    image: imaotai-web:latest
    build:
      context: .
      dockerfile: ./web.Dockerfile
    container_name: imaotai-web
    volumes:
      - ./templates/web.conf:/etc/nginx/conf.d/web.conf
      - ./volumes/web/log:/var/log/nginx
    privileged: true
    networks:
      - imaotai_net
    ports:
      - 80:80
    depends_on:
      - imaotai-api
    restart: always

networks:
  imaotai_net:
    name: imaotai_net